services:
  postgres:
    image: postgres:16
    container_name: financemanager_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: financemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - financemanager_pgdata:/var/lib/postgresql/data
      # optional init scripts:
      # - ./init:/docker-entrypoint-initdb.d

volumes:
  financemanager_pgdata: